kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-app
spec:
  replicas: 1
  selector:
      matchLabels:
          app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
      - name: backend
        image: asia-south1-docker.pkg.dev/clowder-403113/testing/test-app:latest
        ports: 
          - containerPort: 8080
        resources: 
          requests:
            memory: "128Mi"
            cpu: "250m"
            ephemeral-storage: "512Mi"
          limits:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "512Mi"

